""" 4.1.10_Python_TYPE_CONV_FUNC_LIST """

# ----------

list () # Converts a value to a list.

# ----------

# String to list conversion
print(list("Hello"))  # Output: ['H', 'e', 'l', 'l', 'o']

# Tuple to list conversion
print(list((1, 2, 3)))  # Output: [1, 2, 3]

# Set to list conversion
print(list({1, 2, 3}))  # Output: [1, 2, 3]

# Dictionary to list conversion
print(list({"a": 1, "b": 2}))  # Output: ['a', 'b']

# ----------
# ----------

""" (FOOTNOTE) """

list () # As a constructor, it creates a list object.
# Assigning a LIST value to a variable

my_list = list([1, 2, 3])
print(my_list)  # Output: [1, 2, 3]

# ---------