""" 4.10.0_Python_SPECIAL_LOW_LEVEL_FUNCTIONS """

# ----------

""" Special Low-Level Functions (SPE_LOW_LVL_FUNC) """

bin() # Converts an integer to a binary string.
oct() # Converts an integer to an octal string.
hex() # Converts an integer to a hexadecimal string.
breakpoint() # Drops into debugger.
__import__() # Dynamically imports a module.
aiter() # Returns an async iterator.
anext() # Gets the next item from an async iterator.

# ----------