""" 4.4.0_Python_INTROSPECTION_FUNCTIONS """

# ----------

""" Introspection Functions (INT_FUNC) """

type() # Returns the type of an object.
id() # Returns the memory address of an object.
dir() # Returns a list of valid attributes.
vars() # Returns the __dict__ of an object.
getattr() # Returns the value of a named attribute.
setattr() # Sets the value of a named attribute.
hasattr() # Checks if object has a given attribute.
delattr() # Deletes a named attribute.
callable() # Checks if an object is callable.
hash() # Returns the hash value of an object.

# ----------