""" 4.5.0_Python_ENVIRONMENT_INSPECTION_FUNCTION """

# ----------

""" Environment Inspection and Documentation Functions (ENV_DOC_FUNC) """

globals() # Returns the global symbol table.
locals() # Returns the local symbol table.
isinstance() # Checks if an object is an instance of a class.
issubclass() # Checks if a class is a subclass of another.
help() # Launches the built-in help system.

# ----------